CREATE DATABASE ECOMMERCE_DB
GO

USE ECOMMERCE_DB
GO

CREATE TABLE PRODUCTOS(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	PRECIO MONEY NOT NULL,
	STOCK BIGINT NOT NULL,
	IMG_URL VARCHAR(1000) NULL,
)
GO
