CREATE DATABASE ECOMMERCE_DB
GO

USE ECOMMERCE_DB
GO

CREATE TABLE DIRECCIONES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,CALLE VARCHAR(30) NOT NULL
	,NUMERO INT NOT NULL
	,PISO INT NOT NULL
	,PROVINCIA VARCHAR(30) NOT NULL
	,CP INT NOT NULL
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE PERSONAS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,NOMBRE VARCHAR(30) NOT NULL
	,APELLIDO VARCHAR(30) NOT NULL
	,ID_DIRECCION INT NOT NULL FOREIGN KEY REFERENCES DIRECCIONES(ID)
	,NACIMIENTO DATE NOT NULL
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE USUARIOS_TIPOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,TIPO VARCHAR(50) NOT NULL UNIQUE
)
GO

CREATE TABLE USUARIOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,USERNAME VARCHAR(50) NOT NULL UNIQUE
	,PASSWORD VARCHAR(50) NOT NULL
	,EMAIL VARCHAR(100) NOT NULL
	,ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS_TIPOS(ID)
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO


CREATE TABLE MARCAS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,NOMBRE VARCHAR(50) NOT NULL
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE CATEGORIAS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,NOMBRE VARCHAR(50) NOT NULL
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE TALLES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,MEDIDA VARCHAR(3) NOT NULL 
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE ARTICULOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,CODIGO VARCHAR(4) NOT NULL UNIQUE
	,NOMBRE VARCHAR(100) NOT NULL
	,DESCRIPCION VARCHAR(500) NOT NULL
	,PRECIO MONEY NOT NULL CHECK(PRECIO > 0)
	,STOCK INT NOT NULL CHECK(STOCK > 0) DEFAULT(1)
	,IMG_URL VARCHAR(1000) NULL
	,ID_TALLE INT NULL FOREIGN KEY REFERENCES TALLES(ID)
	,ID_CATEGORIA INT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID)
	,ID_MARCA INT NULL FOREIGN KEY REFERENCES MARCAS(ID)
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE CARRITOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,ID_ARTICULO INT NOT NULL FOREIGN KEY REFERENCES ARTICULOS(ID)
	,PRECIO MONEY NULL
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE CLIENTES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,ID_USUARIO INT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_CARRITO INT NOT NULL FOREIGN KEY REFERENCES CARRITOS(ID)
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE ENVIOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,ID_DIRECCION INT NOT NULL FOREIGN KEY REFERENCES DIRECCIONES(ID)
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE PAGOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,FORMA VARCHAR(50) NOT NULL 
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE VENTAS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1)
	,ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID)
	,ID_CARRITO INT NOT NULL FOREIGN KEY REFERENCES CARRITOS(ID)
	,ID_ENVIO INT NOT NULL FOREIGN KEY REFERENCES ENVIOS(ID)
	,ID_PAGOS INT NOT NULL FOREIGN KEY REFERENCES PAGOS(ID)
	,ESTADO BIT NOT NULL DEFAULT(1)
)
GO


INSERT INTO TALLES (MEDIDA) VALUES ('XS') --ID 1
INSERT INTO TALLES (MEDIDA) VALUES ('S')  --ID 2
INSERT INTO TALLES (MEDIDA) VALUES ('M')  --ID 3
INSERT INTO TALLES (MEDIDA) VALUES ('L')  --ID 4
INSERT INTO TALLES (MEDIDA) VALUES ('XL')  --ID 5
INSERT INTO TALLES (MEDIDA) VALUES ('XXL') --ID 6
INSERT INTO TALLES (MEDIDA) VALUES (34) --ID 7
INSERT INTO TALLES (MEDIDA) VALUES (35) --ID 8
INSERT INTO TALLES (MEDIDA) VALUES (36) --ID 9
INSERT INTO TALLES (MEDIDA) VALUES (37) --ID 10
INSERT INTO TALLES (MEDIDA) VALUES (38) --ID 11
INSERT INTO TALLES (MEDIDA) VALUES (39) --ID 12
INSERT INTO TALLES (MEDIDA) VALUES (40) --ID 13
INSERT INTO TALLES (MEDIDA) VALUES (41) --ID 14
INSERT INTO TALLES (MEDIDA) VALUES (42) --ID 15
INSERT INTO TALLES (MEDIDA) VALUES (43) --ID 16
INSERT INTO TALLES (MEDIDA) VALUES (44) --ID 17
INSERT INTO TALLES (MEDIDA) VALUES (45) --ID 18
INSERT INTO TALLES (MEDIDA) VALUES (46) --ID 19
INSERT INTO TALLES (MEDIDA) VALUES (47) --ID 20
INSERT INTO TALLES (MEDIDA) VALUES ('...') --ID 21

INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Remera') --ID 1
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Pantalón') --ID 2
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Calzado') --ID 3
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Campera') --ID 4
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Buzo') --ID 5
INSERT INTO CATEGORIAS (NOMBRE) VALUES ('Accesorio') --ID 6

INSERT INTO MARCAS (NOMBRE) VALUES ('The North Face') --ID 1
INSERT INTO MARCAS (NOMBRE) VALUES ('Nike') --ID 2
INSERT INTO MARCAS (NOMBRE) VALUES ('Adidas') --ID 3
INSERT INTO MARCAS (NOMBRE) VALUES ('Puma') --ID 4
INSERT INTO MARCAS (NOMBRE) VALUES ('Vans') --ID 5



INSERT INTO USUARIOS_TIPOS (TIPO) VALUES ('Cliente');
INSERT INTO USUARIOS_TIPOS (TIPO) VALUES ('Admin');

INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, ID_TIPO)
VALUES ('Juan Carlos','123','jcarlos@gmail.com','1');

INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, ID_TIPO)
VALUES ('Jose','456','jose@gmail.com','2');




INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'ZA01'
	,'Zapatilla Filmore Decon'
	,'Las Filmore Decon son zapatillas de corte bajo confeccionadas con una lona duradera.'
	,9400
	,12
	,'https://mmgrim2.azureedge.net/MediaFiles/Grimoldi/2020/12_21/0/93/213/6149508.jpg'
	,12
	,3
	,5
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'RA00'
	,'Remera OTW Boys -LOGO'
	,'100% Algodón. Remera para niños. Grifa de marca en ruedo de marca.'
	,2200
	,18
	,'https://grimoldimediamanager.grimoldi.com/MediaFiles/Grimoldi/2021/3_16/0/97/139/6392774.jpg'
	,2
	,1
	,5
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'ZA02'
	,'Zapatilla AIR Force'
	,'Nike Air Force 1 07 con capas de cuero sintético, te ofrece un look urbano y moderno.'
	,12500
	,5
	,'https://www.moovbydexter.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dw8abed4db/products/NI_315115-112/NI_315115-112-1.JPG'
	,10
	,3
	,2
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'G10I'
	,'Gorro Standard Issue Beanie'
	,'Un clásico para estar al aire libre, de tela polar con un secado rápido.'
	,8190
	,10
	,'https://mmgrim2.azureedge.net/MediaFiles/Grimoldi/2018/6_1/0/46/4/3015836.jpg'
	,21
	,6
	,1
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'RA0Q'
	,'Remera Classic'
	,'100% Algodón. Remera masculina. Escote redondo.'
	,7200
	,10
	,'https://mmgrim2.azureedge.net/MediaFiles/Grimoldi/2021/10_6/0/108/98/7103176.jpg'
	,5
	,1
	,5
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'AC0X'
	,'Mochila Startle BackPack'
	,'La mochila Startle Backpack tiene un compartimento acolchado para laptop.'
	,6400
	,5
	,'https://mmgrim2.azureedge.net/MediaFiles/Grimoldi/2020/11_11/0/90/216/5953624.jpg'
	,21
	,6
	,5
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'JA05'
	,'Campera NeedlePoint Jacket'
	,'Campera canguro Unisex. Detalles bordeados. Estampa en el delantero y parte trasera.'
	,14200
	,7
	,'https://grimoldimediamanager.grimoldi.com/MediaFiles/Grimoldi/2021/8_25/0/107/108/7040162.jpg'
	,4
	,4
	,5
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'KS03'
	,'Pantalón Classics Cargo Wv'
	,'Pantalón deportivo o casual. El cordón de la cintura elástica te permite personalizar el ajuste.'
	,7000
	,15
	,'https://www.moovbydexter.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dw93c41525/products/PU_532160-01/PU_532160-01-1.JPG'
	,3
	,2
	,4
);

INSERT INTO ARTICULOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMG_URL, ID_TALLE, ID_CATEGORIA, ID_MARCA)
VALUES (
	'ZX03'
	,'Zapatilla Forum Low'
	,'Cuero Sintético/ Suela: Goma. Mix de materiales Low.'
	,12900
	,14
	,'https://www.moovbydexter.com.ar/on/demandware.static/-/Sites-dabra-catalog/default/dwb55abc9b/products/AD_H01924/AD_H01924-1.JPG'
	,17
	,3
	,3
);

SELECT * FROM ARTICULOS